### ISSUE TITLE
Création d'un fichier requirements.txt

### ISSUE THREAD

**Issue by romsson** [AmigoCap/GPSFlow#1]
J'ai l'erreur suivante quand j'execute `1-Display.ipynb`

> ImportError: No module named 'mpl_toolkits.basemap'

Il faudrait mettre tous les modules que vous utilisez dans un fichier `requirements.txt` afin de pouvoir les installer en une seule fois avec `pip` (voir https://pip.pypa.io/en/stable/user_guide/#requirements-files

**Comment by romsson** [comment]
Je n'ai pas Conda donc voir si il est possible d'installer Basemap avec PIP seulement (visiblement c'est pas possible https://askubuntu.com/questions/555474/problem-importing-a-module-mpl-toolkits-basemap-in-python)

**Comment by thalkz** [comment]
Apparemment il faut installer avec les sources. De toute façon je pense qu'on n'utilisera plus Basemap, mais plutôt une combinaison de gmap et pyplot.
