### ISSUE TITLE
Pb avec nbviewer

### ISSUE THREAD

**Issue by romsson** [AmigoCap/GPSFlow#2]
Nbviewer permet de visualiser des notebooks hébergés sur GitHub de la façon suivante

http://nbviewer.jupyter.org/github/AmigoCap/GPSFlow/blob/master/2-Preprocessing.ipynb

Par contre le rendu n'est pas bon comme ci dessous

<img width="1441" alt="screen shot 2018-02-01 at 1 42 12 pm" src="https://user-images.githubusercontent.com/586236/35679000-b8d0747a-0755-11e8-821b-705a8fa31656.png">

Voici un exemple de bon rendu

http://nbviewer.jupyter.org/github/romsson/mixit16-simple-dataviz-datascience/blob/master/simple-dataviz-datascience.ipynb

Si possible essayer de voir d'où vien le pb et ensuite partager les liens vers vos notebooks en utilisant nbviewer

**Comment by thalkz** [comment]
C'est fix, mais nbviewer semble garder les anciennes versions en cache... Si ça s'affiche toujours mal, il faut ajouter "?flush_cache=true" à la fin de l'url :

https://nbviewer.jupyter.org/github/AmigoCap/GPSFlow/blob/master/1-Display.ipynb?flush_cache=true
